# Generated by Django 3.1.3 on 2020-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hastag',
            field=models.TextField(default=False),
        ),
    ]
