# Generated by Django 3.1.3 on 2020-11-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201102_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hastag',
            field=models.TextField(blank=True),
        ),
    ]
